// Fetch Swiss cantonal flag SVGs into public/flags/<AB>.svg, cached in the repo
// so the app has no runtime dependency on a third party.
//
// Run:  npm run flags               (skips files already present)
//       npm run flags -- --force    (re-download everything)
//
// Source: https://github.com/ylerjen/swiss-flags (MIT), served over jsDelivr and
// pinned to a commit SHA so the artwork is reproducible. Every canton is present
// upstream with a consistent 24.03 × 29 viewBox, so no geometric fallbacks are
// needed — a canton that cannot be fetched fails the run loudly instead of
// silently shipping a wrong flag.

import { mkdir, writeFile, readFile, access } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '..', 'public', 'flags')

const UA =
  'bundeshaus-pack/0.1 (Swiss Parliament card game; educational prototype)'

const REPO = 'ylerjen/swiss-flags'
// Pinned commit — bump deliberately, never track a moving branch.
const REF = '68d246174f297e07e5dca5d9df051cd819537149'
const MIRRORS = [
  (ab) => `https://cdn.jsdelivr.net/gh/${REPO}@${REF}/cantons/${ab}.svg`,
  (ab) => `https://raw.githubusercontent.com/${REPO}/${REF}/cantons/${ab}.svg`,
]

// prettier-ignore
const CANTONS = [
  'ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL',
  'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU',
]

// The smallest upstream flag (FR) is ~900 bytes; anything below this is a
// truncated download or a placeholder left by an earlier version of this script.
const MIN_BYTES = 500

const ATTRIBUTION = `Swiss cantonal flags in this directory are generated by scripts/fetch-flags.mjs.

Source:  https://github.com/${REPO}
Licence: MIT
Commit:  ${REF}

Do not edit these files by hand — run \`npm run flags -- --force\` instead.
`

function isValidSvg(body) {
  return (
    body.includes('<svg') && body.includes('</svg>') && body.length >= MIN_BYTES
  )
}

async function download(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return await res.text()
}

async function fetchFlag(ab) {
  const errors = []
  for (const mirror of MIRRORS) {
    const url = mirror(ab.toLowerCase())
    try {
      const svg = await download(url)
      if (!isValidSvg(svg)) throw new Error(`unexpected body (${svg.length} B)`)
      return svg
    } catch (e) {
      errors.push(`${url}: ${e.message}`)
    }
  }
  throw new Error(errors.join('\n    '))
}

async function cachedFlag(path) {
  try {
    await access(path)
  } catch {
    return null
  }
  const body = await readFile(path, 'utf8')
  return isValidSvg(body) ? body : null
}

async function main() {
  await mkdir(OUT, { recursive: true })
  const force = process.argv.includes('--force')

  let fetched = 0
  let cached = 0
  const failed = []

  const results = await Promise.all(
    CANTONS.map(async (ab) => {
      const out = join(OUT, `${ab}.svg`)
      if (!force && (await cachedFlag(out))) return { ab, status: 'cached' }
      try {
        const svg = await fetchFlag(ab)
        await writeFile(out, svg)
        return { ab, status: 'fetched', size: svg.length }
      } catch (e) {
        return { ab, status: 'failed', message: e.message }
      }
    }),
  )

  for (const r of results) {
    if (r.status === 'cached') {
      cached++
    } else if (r.status === 'fetched') {
      fetched++
      process.stdout.write(`✓ ${r.ab}  (${(r.size / 1024).toFixed(1)} kB)\n`)
    } else {
      failed.push(r.ab)
      process.stderr.write(`✗ ${r.ab}\n    ${r.message}\n`)
    }
  }

  await writeFile(join(OUT, 'ATTRIBUTION.txt'), ATTRIBUTION)

  process.stdout.write(
    `\nflags: ${fetched} fetched, ${cached} cached, ${failed.length} failed → ${OUT}\n`,
  )

  if (failed.length) {
    process.stderr.write(`\nMissing flags: ${failed.join(', ')}\n`)
    process.exitCode = 1
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
